version: '3'
services:
  api:
    build:
      context: .
      dockerfile: .dockerfiles/Dockerfile-api
    ports:
      - "5051:5000"
    restart: on-failure:10
  web:
    build:
      context: .
      dockerfile: .dockerfiles/Dockerfile-web
    links:
      - api:api
    depends_on:
      - api
    ports:
      - "8085:8000"
    restart: on-failure:10
