FROM python:3.6.7-alpine3.8

EXPOSE 8000

RUN mkdir -p /srv/app/web

COPY ./web /srv/app/web
WORKDIR /srv/app

ENV FLASK_APP=web/app.py
ENV FLASK_ENV=production
RUN apk add --update gcc make g++ openssl-dev
RUN pip install --upgrade pip
RUN pip install -r web/requirements/dev-requirements.txt --user

CMD  python -m flask run --port 8000 --host 0.0.0.0